In [ ]:
import numpy as np


my_list = [1,2,3]
my_array = np.array([1,2,3])
print(type(my_list))

<class 'list'>


In [ ]:
print(np.array(my_list))

[1 2 3]


In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(np.array(my_matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(np.arange(0,10))

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
print(np.arange(0,11,2))

[ 0  2  4  6  8 10]


In [ ]:
print(np.zeros(3))

[0. 0. 0.]


In [ ]:
print(np.zeros((5,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
print(np.zeros(3))

[0. 0. 0.]


In [ ]:
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print(np.linspace(0,10,3))

[ 0.  5. 10.]


In [ ]:
print(np.linspace(0,5,20))

[0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]


In [ ]:
print(np.linspace(0,5,21))

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25
 3.5  3.75 4.   4.25 4.5  4.75 5.  ]


In [ ]:
print(np.random.rand(2))

[0.67122527 0.82987952]


In [ ]:
print(np.random.rand(5,5))

[[0.66718189 0.95785746 0.782595   0.85078342 0.76218188]
 [0.22108216 0.40254193 0.64845509 0.73302634 0.12576072]
 [0.46553657 0.59035817 0.09914067 0.67542473 0.67902462]
 [0.35183284 0.12712814 0.29415467 0.84076486 0.41033271]
 [0.36147285 0.05076536 0.15123087 0.32983636 0.83899201]]


In [ ]:
print(np.random.randn(2))   #From normal distribution

[ 0.46647937 -1.9747091 ]


In [ ]:
print(np.random.randn(5,5))

[[ 0.27554801 -1.57580517  1.56839691 -0.72479502  0.30588972]
 [ 1.16394216 -1.04909539 -0.97657801 -0.63905079  1.69742923]
 [-1.2861153  -0.18916158 -0.07391267 -0.16049537 -0.10879348]
 [-0.69698401 -1.00581081 -0.39254505 -2.1377931   1.76093089]
 [-0.77419323 -0.53023393 -0.79351601  0.29190243 -1.22200536]]


In [ ]:
print(np.random.randint(1,100))

93


In [ ]:
print(np.random.randint(1,100,10))

[ 6 97 89 38 36  5 60 60 50 22]


In [ ]:
#seeding for reproducable result
np.random.seed(77)

print(np.random.rand(4))   # 4 random numbers

[0.91910903 0.6421956  0.75371223 0.13931457]


In [ ]:
np.random.seed(77)
print(np.random.rand(4))

[0.91910903 0.6421956  0.75371223 0.13931457]


In [ ]:
#Storing

arr = np.arange(25) # numbers from 0 to 24
ranarr = np.random.randint(0,50,10)
print(arr)
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[32 39 44 19 32 36 36 47 14 15]


In [ ]:
#reshape: Returns an array containing the same data with a new shape

print(arr.reshape(5,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
#Min , Max and their index position

print(ranarr.max())
print(ranarr.argmax())
print(ranarr.min())

47
7
14


**Indexing and Slicing**

In [ ]:
import numpy as np

arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
#Get a value at an index
print(arr[8])

8


In [ ]:
#get a value in a range

print(arr[1:5])
print(arr[0:5])

[1 2 3 4]
[0 1 2 3 4]


In [ ]:
#Broadcasting
#Setting a value with index range   (Broadcasting)
arr[0:5] = 100
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


In [ ]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:

#Important notes
slice_of_arr = arr[0:6]
print(slice_of_arr)

[0 1 2 3 4 5]


In [ ]:
# Change Slice
slice_of_arr[:] = 99
print(slice_of_arr)
print(arr)

# Changes made are also there in our original array!
# Data is not copied ,it is the view of the original array!
# This avoids memory problem

[99 99 99 99 99 99]
[99 99 99 99 99 99  6  7  8  9 10]


In [ ]:

# To get a copy, we need to be explicit
arr_copy = arr.copy()
print(arr_copy)

[99 99 99 99 99 99  6  7  8  9 10]


**Conditional Selection**

In [ ]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#check each element of the array against the condition
#which returns a bollean array where each element is true if the corresponding element in array
#and flase otherwise
print(arr>4)

[False False False False  True  True  True  True  True  True]


In [ ]:
#store boolean rresluts in another array
bool_arr = arr>4
print(bool_arr)

[False False False False  True  True  True  True  True  True]


In [ ]:
print(arr[bool_arr])

[ 5  6  7  8  9 10]


In [ ]:
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#basic arithmetic
print(arr+ arr)
print(arr* arr)
print(arr-arr)

[ 0  2  4  6  8 10 12 14 16 18]
[ 0  1  4  9 16 25 36 49 64 81]
[0 0 0 0 0 0 0 0 0 0]


In [ ]:
#this will raaise a warning on division by zero but not an error!
#it just fills the spot with nan
print(arr/arr)

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]


<ipython-input-42-a78f197acbd2>:3: RuntimeWarning: invalid value encountered in divide
  print(arr/arr)


In [ ]:
#also a warning but not an error related to infinity
print(1/arr)

[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]


<ipython-input-43-194edbe1975c>:2: RuntimeWarning: divide by zero encountered in divide
  print(1/arr)


In [ ]:
print(arr**3)

[  0   1   8  27  64 125 216 343 512 729]


In [ ]:
#universal functions
print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))
print(np.sin(arr))


[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]


<ipython-input-46-8cffdca2df4b>:4: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr))


In [ ]:
#SUmmary statistics
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.var())
print(arr.std())


45
4.5
9
0
8.25
2.8722813232690143


In [ ]:
#2d array
#this is a 2 dimensional array with 3 rows and 4 columns
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#rows and column count
print(arr_2d.shape)   #shape is a property not a method so it doesnt require brackets after it

(3, 4)


In [ ]:
#sum all the columns for each row(e.g. 1+5+9, 2+6+10, ,etc)
print(arr_2d.sum(axis =0))

[15 18 21 24]


In [ ]:
#sum all the columns for each row(e.g. 1+5+9, 2+6+10, ,etc)
print(arr_2d.sum(axis =1))

[10 26 42]


# ** Exercise**

In [ ]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
arr = np.ones(10)*5
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
print(np.arange(10,50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
print(np.arange(10,50,2))

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [ ]:
print(np.array())