In [63]:
import numpy as np
import pandas as pd
import random

In [4]:
# 1. Write a NumPy program to get the numpy version and show numpy build configuration.
np.__version__

'1.26.4'

In [10]:
# 2. Write a NumPy program to get help on the add function.
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a+b
print(c)

[5 7 9]


In [12]:
# 3. Write a NumPy program to test whether none of the elements of a given array is zero.
x = np.array([0,1,2,3,4])
print(np.all(x))

False


In [13]:
# 4. Write a NumPy program to test whether any of the elements of a given array is non-zero.

x = np.array([1,2,3,4])
print(np.all(x))

True


In [14]:
# 5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).

print(np.isfinite(x))

[ True  True  True  True]


In [15]:
# 6. Write a NumPy program to test element-wise for positive or negative infinity.

print(np.isinf(x))

[False False False False]


In [16]:
# 7. Write a NumPy program to test element-wise for NaN of a given array.
print(np.isnan(x))

[False False False False]


In [20]:
# 8. Write a NumPy program to test element-wise for complex number, real number of a given array. Also
# test whether a given number is a scalar type or not.
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])

print(np.iscomplex(a))



[ True False False False False  True]


In [18]:
print(np.isreal(a))

[False  True  True  True  True False]


In [38]:
a = np.array(2)
np.isscalar([a])

False

In [36]:
print(np.isscalar(5))

True


In [43]:
# 9. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and
# less_equal) of two given arrays.
x = np.array([1,4,5,6,9])
y = np.array([3,2,4,8,9])

np.greater(x,y)


array([False,  True,  True, False, False])

In [44]:
np.greater_equal(x,y)

array([False,  True,  True, False,  True])

In [45]:
np.less(x,y)

array([ True, False, False,  True, False])

In [47]:
np.less_equal(x,y)

array([ True, False, False,  True,  True])

In [52]:
# 10. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the
# memory occupied by the array.

a = np.array([1, 7, 13, 105])
a.nbytes #memory in bytes

32

In [56]:
# 11. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [55]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [57]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [58]:
# 12. Write a NumPy program to create an array of the integers from 30 to70.
np.arange(30,70)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69])

In [59]:
# 13. Write a NumPy program to create an array of all the even integers from 30 to 70.

np.arange(30,70,2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68])

In [61]:
# 14. Write a NumPy program to create a 3x3 identity matrix.

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [76]:
# 15. Write a NumPy program to generate a random number between 0 and 1.

np.random.rand(1)

array([0.75633695])

In [77]:
# 16. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

np.random.randn(15)

array([-1.24034953, -0.3535119 , -0.18558821,  1.30542042,  0.52752139,
        1.47822869, -0.17347522,  0.42898308,  1.398793  ,  0.14567077,
        0.20050291,  1.55283997, -0.66907486, -1.19105477,  0.26003955])

In [82]:
# 17. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values
# except the first and last.

a = np.arange(15,56)
print(a)
slice = a[1:-1]
print(slice)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [88]:
# 18. Write a NumPy program to create a 3X4 array.

np.random.randint(1,10,(3,4))

array([[4, 4, 2, 1],
       [2, 9, 7, 9],
       [1, 4, 8, 6]])

In [89]:
# 19. Write a NumPy program to create a vector of length 10 with values evenly distributed
# between 5 and 50.

np.linspace(5,50,10)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [116]:
# 20. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the
# numbers in the range from 9 to 15.

a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [118]:
slice_of_arr = (-(a[9:16]))
print(slice_of_arr)
print(a)

[ -9 -10 -11 -12 -13 -14 -15]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [111]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [142]:
# 21. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.
np.random.randint(0,10,5)

array([4, 6, 2, 9, 3])

In [100]:
# 22. Write a NumPy program to multiply the values of two given vectors.
a = np.arange(5)
print(a)
print(a * a)

[0 1 2 3 4]
[ 0  1  4  9 16]


In [113]:
# 23. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

a = np.random.randint(10,21,(3,4))
a

array([[17, 19, 16, 17],
       [18, 11, 11, 12],
       [11, 19, 16, 18]])

In [114]:
# 24. Write a NumPy program to find the number of rows and columns of a given matrix.

print(a.shape)
rows = a.shape[0]
print(rows)
col = a.shape[1]
print(col)

(3, 4)
3
4


In [120]:
# 25. Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0.

np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [133]:
# 26. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be
# equal to 1, and inside 0.

a = np.ones((10,10))
a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [145]:
# 27. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2,
# 3, 4, 5.
a = np.diag([1,2,3,4,5])
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [146]:
# 28. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.

np.random.randint(10,50,(3,3,3))

array([[[11, 33, 21],
        [42, 36, 20],
        [45, 30, 39]],

       [[41, 13, 41],
        [39, 24, 18],
        [21, 41, 21]],

       [[49, 19, 17],
        [29, 42, 43],
        [32, 48, 19]]])

In [147]:
# 29. Write a NumPy program to compute the inner product of two given vectors.

a = np.array([1,2,3])
b = np.array([3,4,5])
np.dot(a,b)

26

In [149]:
# 30. Write a NumPy program to sort a given array by row and column in ascending order.

a = np.array([[11, 33, 21],
        [42, 36, 20],
        [45, 30, 39]])

row = np.sort(a)
row

array([[11, 21, 33],
       [20, 36, 42],
       [30, 39, 45]])

In [153]:
col = np.sort(a,axis = 0)
col

array([[11, 30, 20],
       [42, 33, 21],
       [45, 36, 39]])

In [156]:
# 31. Write a NumPy program to extract all numbers from a given array which are less and greater
# than a specified number.

np.extract(a>25,a)

array([33, 42, 36, 45, 30, 39])

In [161]:
# 32. Write a NumPy program to replace all numbers in a given array which is equal, less and greater to a
# given number.
arr = np.array([1,5,8,9,12,36,77])
number  = 10
arr = np.where(arr < number,1,arr)
arr = np.where(arr > number,0,arr)
arr

array([1, 1, 1, 1, 0, 0, 0])

In [163]:
# 33. Write a NumPy program to create an array of equal shape and data type of a given array.

x = np.random.randint(1,10,(3,3))
print(x)
print(x.dtype)

[[7 2 2]
 [8 2 3]
 [5 1 9]]
int64


In [164]:
# 34. Write a NumPy program to create a three-dimension array with shape (3,5,4) and set to a variable

a = np.random.randint(1,100,(3,5,4))
a

array([[[47, 32, 35, 51],
        [42, 24, 18, 92],
        [23, 41, 40, 35],
        [71, 10, 75, 10],
        [80, 87, 36, 47]],

       [[50, 81,  4,  8],
        [33, 60, 45, 71],
        [12,  2,  5, 29],
        [65, 48, 57, 54],
        [58, 79, 39, 21]],

       [[93, 35,  1, 29],
        [43, 87, 35, 56],
        [38, 72, 95, 49],
        [22, 97,  5, 68],
        [86, 56, 53, 45]]])

In [165]:
# 35. Write a NumPy program to multiply two given arrays of same size element-by-element.

nums1 = np.array([[2, 5, 2],
              [1, 5, 5]])

nums2 = np.array([[5, 3, 4],
              [3, 2, 5]])

np.multiply(nums1,nums2)

array([[10, 15,  8],
       [ 3, 10, 25]])